--- 
# Tasks necessary on the basion host
#
# Example Usage:
# 
# ansible-playbook ansible/bastion-tasks.yml

- name: Get MAC addresses for all virtual workers
  hosts: hypervisor
  gather_facts: false
  vars_files:
  - vars/all.yml
  - vars/lab.yml
  roles:
  - bastionhost
