---
# Setup for the hypervsor nodes to host virtual machines that act as worker nodes
#
# Example usage:
#
# ansible-playbook -i ansible/inventory/cloud29.local ansible/hv-setup.yaml

- name: Setup hypervisor machines to host virtual worker nodes
  hosts: hv
  vars_files:
  - vars/hv.yml
  - vars/lab.yml
  roles:
    - hv-install
    - hv-networking
    - hv-libvirt
      #- hv-worker-create-vms
