---
# Configure dnsmasq
#
# Example Usage:
#
# ansible-playbook ansible/configure-dnsmasq.yml
#

- name: Configure dnsmasq
  hosts: hv
  vars_files:
  - vars/hv.yml
  - vars/lab.yml
  roles:
  - dnsmasq-install