---
# Setup for the hypervsor nodes to host virtual machines that act as worker nodes
#
# Example usage:
#
# ansible-playbook -i ansible/inventory/cloud29.local ansible/hv-setup.yaml

- name: Deploy ssh keys to hv nodes
  hosts: hv
  vars_files:
  - vars/all.yml
  - vars/lab.yml
  roles:
    - hv-deploy-keys