---
# dEploy ssh skyes to hv nodes
#
# Example usage:
#
# ansible-playbook -i ansible/inventory/cloud29.local ansible/hv-deploy-keys.yaml

- name: Deploy ssh keys to hv nodes
  hosts: hv
  vars_files:
  - vars/hv.yml
  roles:
    - hv-deploy-keys